### ISSUE TITLE
Connection issue after Gateway Update

### ISSUE THREAD

**Issue by add30417** [scruss/ihsctrl#2]
Dear All,

as you know, IKEA updated the gateway software by end of June. After this software update, many issues happen for all 3rd party tools (like this project).

I would like use this project longer in my environment. Do you will update ihsctrl for interaction with IKEA gateway?

Thanks
Daniel

**Comment by scruss** [comment]
I didn't know that IKEA had updated the gateway software. All I'd noticed is that these tools run very slowly now.

They still work for me. I don't know what I'd need to do to update the software. Let me check on that.

**Comment by add30417** [comment]
Sorry, but for your tool suite still isn't working. I'm using 14 devices with the gateway version 1.15.34.

I have a failure rate of around 95% when using the ihsctrl tools. 
After the fix applied from other control tools (e.g. https://github.com/home-assistant-libs/pytradfri), there tools working fine again with the new gateway version.

Honestly, I don't want change the tools and stay with ihsctrl, but if it not working anymore, I have to change it. Even I like your simple approach.

**Comment by scruss** [comment]
What version is your libcoap2-bin? I'm running 4.2.x on all my machines, and this works for me. I have the same gateway version as you.

I can't find any definitive documentation on what changed with the IHS protocol, although your link was helpful, thanks. I suspect that the gateway is holding the connection open fractionally longer than it used to, and it's failing for you. I can get slightly better performance  through using `coap-client-openssl` instead of `coap-client-gnutls`, but each query still takes about a second.

I'm in a bind. I want to make this work for you, but I can't repeat your problem. I'm having severe health issues right now, and I don't really have the spoons to deal with this.

**Comment by add30417** [comment]
Well, one second is fine for me. Sometimes ihslist shows no entry at my pi.

I'm using the following Version, with the latest raspbian os.

libcoap2 is already the newest version (4.2.0-2).
libcoap2-bin is already the newest version (4.2.0-2).
